-- Copyright (c) 2026 Scott Armstrong and Amélie Loher. All rights reserved.
-- Released under Apache 2.0 license as described in the file LICENSE.
module

public import HeatKernel.Bridge.StationaryLebesguePairing
public import HeatKernel.Bridge.CoreTests
import Mathlib.Tactic

/-! # Continuous form tests generated by square-integrable space-time data -/

@[expose] public section
noncomputable section
open Set MeasureTheory TopologicalSpace
namespace HeatKernel

variable {α : Type*} [MeasurableSpace α] (μ : Measure α) [IsFiniteMeasure μ]
    {N q : ℕ} (X : Fin q → (Fin N → ℝ) → (Fin N → ℝ))

/-- A square-integrable value term and flux define a continuous linear functional
on the horizontal form domain. -/
def timeIntegratedFormTest
    (T : Lp ℝ 2 (μ.prod (volume.restrict ((⊤ : Opens (Fin N → ℝ)) : Set (Fin N → ℝ)))))
    (F : Fin q → Lp ℝ 2 (μ.prod (volume.restrict ((⊤ : Opens (Fin N → ℝ)) : Set (Fin N → ℝ))))) :
    energyGraph (N := N) ⊤ X →L[ℝ] ℝ :=
  (stationaryLpPairing μ _ T).comp (energyInclusion ⊤ X) +
    ∑ i, (stationaryLpPairing μ _ (F i)).comp
      ((PiLp.proj 2 (fun _ : Fin q => SpatialL2 (⊤ : Opens (Fin N → ℝ))) i).comp
        (energyGradient ⊤ X))

/-- The continuous functional is the sum of the concrete value and flux pairings. -/
theorem timeIntegratedFormTest_apply
    (T : Lp ℝ 2 (μ.prod (volume.restrict ((⊤ : Opens (Fin N → ℝ)) : Set (Fin N → ℝ)))))
    (F : Fin q → Lp ℝ 2 (μ.prod (volume.restrict ((⊤ : Opens (Fin N → ℝ)) : Set (Fin N → ℝ)))))
    (v : energyGraph (N := N) ⊤ X) :
    timeIntegratedFormTest μ X T F v =
      (∫ z : α × (Fin N → ℝ), T z * (v : GradientSpace (N := N) ⊤ q).fst z.2 ∂μ.prod volume) +
      ∑ i, ∫ z : α × (Fin N → ℝ), F i z * (v : GradientSpace (N := N) ⊤ q).snd i z.2
        ∂μ.prod volume := by
  simp [timeIntegratedFormTest, stationaryLpPairing_apply]
  exact congrArg (fun f : SpatialL2 (⊤ : Opens (Fin N → ℝ)) =>
    ∫ z : α × (Fin N → ℝ), T z * f z.2 ∂μ.prod volume) (energyInclusion_apply ⊤ X v)

/-- A time-integrated form test that vanishes on smooth interior tests vanishes
on every zero-boundary form test. All integrability is carried by its L² data. -/
theorem timeIntegratedFormTest_eq_zero_of_core (V : Opens (Fin N → ℝ))
    (T : Lp ℝ 2 (μ.prod (volume.restrict ((⊤ : Opens (Fin N → ℝ)) : Set (Fin N → ℝ)))))
    (F : Fin q → Lp ℝ 2 (μ.prod (volume.restrict ((⊤ : Opens (Fin N → ℝ)) : Set (Fin N → ℝ)))))
    (hcore : ∀ w : energyGraph (N := N) ⊤ X,
      (w : GradientSpace (N := N) ⊤ q) ∈ interiorGradientPairs V X →
        timeIntegratedFormTest μ X T F w = 0)
    (v : zeroBoundaryGraph V X) :
    timeIntegratedFormTest μ X T F ⟨v, zeroBoundaryGraph_le_energyGraph V X v.property⟩ = 0 :=
  eq_zero_on_zeroBoundaryGraph_of_eq_zero_on_core V X
    (timeIntegratedFormTest μ X T F).continuous hcore v

end HeatKernel
