-- Copyright (c) 2026 Scott Armstrong and Amélie Loher. All rights reserved.
-- Released under Apache 2.0 license as described in the file LICENSE.
module
public import RothschildStein.G3.JacobiNormalization
public import Mathlib.Algebra.Lie.Subalgebra
@[expose] public section
noncomputable section
namespace RothschildStein.G3

/-- The scalar span of right-nested words in prescribed generators
(BB Lemma 1.21, p. 12; Lemma 9.70, pp. 471–472). -/
def nestedWordSpan {α L : Type*} (R : Type*) [CommRing R] [LieRing L]
    [LieAlgebra R L] (X : α → L) : Submodule R L :=
  Submodule.span R (Set.range (fun u : Nested α => u.eval X))

/-- Normal-form combinations belong to the nested-word span (BB p. 12). -/
theorem combination_mem_nestedWordSpan {α L R : Type*} [CommRing R] [LieRing L]
    [LieAlgebra R L] (X : α → L) (c : List (ℤ × Nested α)) :
    evaluateCombination X c ∈ nestedWordSpan R X := by
  induction c with
  | nil => exact Submodule.zero_mem _
  | cons z c ih =>
    change z.1 • z.2.eval X + evaluateCombination X c ∈ _
    have hmem : z.2.eval X ∈ nestedWordSpan R X := Submodule.subset_span ⟨z.2, rfl⟩
    exact Submodule.add_mem _ (zsmul_mem hmem z.1) ih

/-- The nested-word span is bracket-closed over every scalar ring
(BB Lemma 1.21, p. 12). -/
theorem nestedWordSpan_lie_mem {α L R : Type*} [CommRing R] [LieRing L]
    [LieAlgebra R L] (X : α → L) {f g : L}
    (hf : f ∈ nestedWordSpan R X) (hg : g ∈ nestedWordSpan R X) :
    ⁅f, g⁆ ∈ nestedWordSpan R X := by
  induction hf using Submodule.span_induction with
  | mem f hf =>
    obtain ⟨u, rfl⟩ := hf
    induction hg using Submodule.span_induction with
    | mem g hg =>
      obtain ⟨v, rfl⟩ := hg
      rw [← normalizeBracket_eval]
      exact combination_mem_nestedWordSpan X _
    | zero => simpa only [lie_zero] using (nestedWordSpan R X).zero_mem
    | add g h _ _ hg hh => rw [lie_add]; exact Submodule.add_mem _ hg hh
    | smul r g _ hg => rw [lie_smul]; exact Submodule.smul_mem _ r hg
  | zero => simpa only [zero_lie] using (nestedWordSpan R X).zero_mem
  | add f h _ _ hf hh => rw [add_lie]; exact Submodule.add_mem _ hf hh
  | smul r f _ hf => rw [smul_lie]; exact Submodule.smul_mem _ r hf

/-- Nested-word normal forms realize the Lie subalgebra generated by the
letters, with their scalar coefficients unchanged (BB p. 12). -/
def nestedWordLieAlgebra {α L : Type*} (R : Type*) [CommRing R] [LieRing L]
    [LieAlgebra R L] (X : α → L) : LieSubalgebra R L where
  __ := nestedWordSpan R X
  lie_mem' := nestedWordSpan_lie_mem X

/-- Membership in the generated Lie algebra is precisely membership
in the scalar span of right-nested words (BB Lemma 1.21, p. 12; Lemma 9.70,
pp. 471–472). -/
theorem lieSpan_eq_nestedWordLieAlgebra {α L R : Type*} [CommRing R] [LieRing L]
    [LieAlgebra R L] (X : α → L) :
    LieSubalgebra.lieSpan R L (Set.range X) = nestedWordLieAlgebra R X := by
  apply le_antisymm
  · apply LieSubalgebra.lieSpan_le.mpr
    rintro _ ⟨i, rfl⟩
    exact Submodule.subset_span ⟨Nested.letter i, rfl⟩
  · change nestedWordSpan R X ≤ (LieSubalgebra.lieSpan R L (Set.range X)).toSubmodule
    apply Submodule.span_le.mpr
    rintro _ ⟨u, rfl⟩
    induction u with
    | letter i => exact LieSubalgebra.subset_lieSpan ⟨i, rfl⟩
    | bracket i u ih => exact LieSubalgebra.lie_mem _ (LieSubalgebra.subset_lieSpan ⟨i, rfl⟩) ih
end RothschildStein.G3
