-- Copyright (c) 2026 Scott Armstrong and Amélie Loher. All rights reserved.
-- Released under Apache 2.0 license as described in the file LICENSE.
module
public import RothschildStein.G3.NestedSpan
public import RothschildStein.G3.SubstitutionComposition
public import RothschildStein.G3.LieSpan
public import Mathlib.Algebra.Algebra.Tower
@[expose] public section
noncomputable section
namespace RothschildStein.G3

instance seriesRationalAlgebra {a : ℕ} : Algebra ℚ (CoefficientSeries a) :=
  Algebra.compHom (CoefficientSeries a) (algebraMap ℚ ℝ)
instance seriesRationalRealScalarTower {a : ℕ} : IsScalarTower ℚ ℝ (CoefficientSeries a) :=
  IsScalarTower.of_algebraMap_eq (fun _ => rfl)
instance finiteWordRationalRealScalarTower {a s : ℕ} {p : Fin a → ℕ+} : IsScalarTower ℚ ℝ (FiniteWordAlgebra a s p) :=
  IsScalarTower.of_algebraMap_eq (fun _ => rfl)

/-- Rational Lie polynomials in the associative completion, generated by
its letters (BB Lemma 9.70, pp. 471–472). -/
def rationalSeriesLieAlgebra (a : ℕ) : LieSubalgebra ℚ (CoefficientSeries a) :=
  LieSubalgebra.lieSpan ℚ (CoefficientSeries a) (Set.range letterSeries)

/-- Rational Lie polynomials in the finite weighted coefficient quotient
(BB Lemma 9.70, pp. 471–472). -/
def rationalCoefficientLieAlgebra (a s : ℕ) (p : Fin a → ℕ+) :
    LieSubalgebra ℚ (FiniteWordAlgebra a s p) :=
  LieSubalgebra.lieSpan ℚ (FiniteWordAlgebra a s p) (Set.range finiteLetter)

/-- Rational Lie polynomials are exactly rational linear combinations of
right-nested words (BB Lemma 1.21, p. 12; Lemma 9.70, pp. 471–472). -/
theorem rationalSeriesLieAlgebra_eq_nested (a : ℕ) :
    rationalSeriesLieAlgebra a = nestedWordLieAlgebra ℚ (letterSeries (a := a)) :=
  lieSpan_eq_nestedWordLieAlgebra _

/-- The same rational normal-form characterization holds in each finite
quotient (BB Lemma 9.70, pp. 471–472). -/
theorem rationalCoefficientLieAlgebra_eq_nested (a s : ℕ) (p : Fin a → ℕ+) :
    rationalCoefficientLieAlgebra a s p = nestedWordLieAlgebra ℚ (finiteLetter (s := s) (p := p)) :=
  lieSpan_eq_nestedWordLieAlgebra _

/-- The fixed real coefficient Lie span regarded as a rational Lie
subalgebra (BB p. 471). -/
def realCoefficientSpanOverRat (a s : ℕ) (p : Fin a → ℕ+) :
    LieSubalgebra ℚ (FiniteWordAlgebra a s p) where
  __ := (finiteLieSpan a s p).restrictScalars ℚ
  lie_mem' := finiteLieSpan_lie_mem

/-- Rational Lie polynomials belong to the fixed real Lie span
(BB pp. 471–472). -/
theorem rationalCoefficientLieAlgebra_mem_real {a s : ℕ} {p : Fin a → ℕ+}
    {f : FiniteWordAlgebra a s p} (hf : f ∈ rationalCoefficientLieAlgebra a s p) :
    f ∈ finiteLieSpan a s p := by
  have hle : rationalCoefficientLieAlgebra a s p ≤ realCoefficientSpanOverRat a s p := by
    apply LieSubalgebra.lieSpan_le.mpr
    rintro _ ⟨i, rfl⟩
    exact nested_mem_finiteLieSpan (Nested.letter i)
  exact hle hf

/-- Rational coefficient Lie elements have positive weighted order
(BB p. 471). -/
theorem rationalCoefficientLieAlgebra_positive {a s : ℕ} {p : Fin a → ℕ+}
    {f : FiniteWordAlgebra a s p} (hf : f ∈ rationalCoefficientLieAlgebra a s p) :
    FiniteOrderAtLeast 1 f :=
  formalSpan_positive_order f (rationalCoefficientLieAlgebra_mem_real hf)

/-- Truncation preserves rational Lie polynomials (BB Lemma 9.70, p. 472). -/
theorem truncateSeries_mem_rationalLieAlgebra {a s : ℕ} {p : Fin a → ℕ+}
    {f : CoefficientSeries a} (hf : f ∈ rationalSeriesLieAlgebra a) :
    truncateSeries f ∈ rationalCoefficientLieAlgebra a s p := by
  let F := (truncateSeries (a := a) (s := s) (p := p)).restrictScalars ℚ
  have hle : rationalSeriesLieAlgebra a ≤ (rationalCoefficientLieAlgebra a s p).comap F.toLieHom := by
    apply LieSubalgebra.lieSpan_le.mpr
    rintro _ ⟨i, rfl⟩
    change finiteLetter i ∈ rationalCoefficientLieAlgebra a s p
    exact LieSubalgebra.subset_lieSpan ⟨i, rfl⟩
  exact hle hf

/-- Substitution of rational Lie polynomials into rational Lie arguments
is a rational Lie polynomial (BB Lemma 9.70, p. 472). -/
theorem finiteSubstitution_mem_rationalLieAlgebra {a b s : ℕ} {p : Fin b → ℕ+}
    (X : Fin a → FiniteWordAlgebra b s p) (hX : ∀ i, FiniteOrderAtLeast 1 (X i))
    (hXL : ∀ i, X i ∈ rationalCoefficientLieAlgebra b s p)
    {f : FiniteWordAlgebra a s (fun _ => 1)}
    (hf : f ∈ rationalCoefficientLieAlgebra a s (fun _ => 1)) :
    finiteSubstitutionHom X hX f ∈ rationalCoefficientLieAlgebra b s p := by
  let F := (finiteSubstitutionHom X hX).restrictScalars ℚ
  have hle : rationalCoefficientLieAlgebra a s (fun _ => 1) ≤
      (rationalCoefficientLieAlgebra b s p).comap F.toLieHom := by
    apply LieSubalgebra.lieSpan_le.mpr
    rintro _ ⟨i, rfl⟩
    change finiteSubstitutionHom X hX (finiteLetter i) ∈ rationalCoefficientLieAlgebra b s p
    rw [finiteSubstitutionHom_letter]
    exact hXL i
  exact hle hf
end RothschildStein.G3
