-- Copyright (c) 2026 Scott Armstrong and Amélie Loher. All rights reserved.
-- Released under Apache 2.0 license as described in the file LICENSE.
module

public import Hormander.Interface.LieWordEval

@[expose] public section

noncomputable section

open Set MeasureTheory
open scoped BigOperators

namespace Hormander.Interface

/-- The Lie words generated by `X` span every tangent direction on `Ω`
(Hörmander's bracket condition). -/
def LieAlgebraSpansOn {k N : ℕ} (Ω : Set (Fin N → ℝ))
    (X : Fin (k + 1) → (Fin N → ℝ) → (Fin N → ℝ)) : Prop :=
  ∀ x ∈ Ω,
    Submodule.span ℝ
      (Set.range (fun w : LieWord k => LieWord.eval X w x)) = ⊤

end Hormander.Interface
